---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: r1
      labels:
        test: 3node
    spec:
      nodeName: node13.dtn.lab
      containers:
        - image: alpine
          name: pod
          command: ["/bin/sh", "-c", "sleep 2000000000000"]
  - apiVersion: v1
    kind: Pod
    metadata:
      name: r2
      labels:
        test: 3node
    spec:
      nodeName: node12.dtn.lab
      containers:
        - image: alpine
          name: pod
          command: ["/bin/sh", "-c", "sleep 2000000000000"]
  - apiVersion: v1
    kind: Pod
    metadata:
      name: r3
      labels:
        test: 3node
    spec:
      nodeName: node13.dtn.lab
      containers:
        - image: alpine
          name: pod
          command: ["/bin/sh", "-c", "sleep 2000000000000"]