apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubedtn
images:
- name: kubedtn
  newName: registry.cn-hangzhou.aliyuncs.com/reins/kubedtn
  newTag: 73cc86e-dirty
- name: registry.cn-hangzhou.aliyuncs.com/reins/kubedtn
  newTag: 1a88c86-dirty
resources:
- namespace.yaml
- serviceaccount.yaml
- rbac.yaml
- daemonset.yaml
- prometheus.yaml
- ../crd
