apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubedtn
images:
- name: kubedtn
  newName: g-lbjv2952-docker.pkg.coding.net/dtn/kubedtn/kubedtn
  newTag: 90fe87a
- name: registry.cn-hangzhou.aliyuncs.com/reins/kubedtn
  newTag: 1a88c86-dirty
resources:
- namespace.yaml
- serviceaccount.yaml
- rbac.yaml
- daemonset.yaml
- prometheus.yaml
- ../crd
