---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedtn-clusterrole
rules:
  - apiGroups:
    - "y-young.github.io"
    resources:
    - topologies
    verbs: ["*"]
  - apiGroups:
    - "y-young.github.io"
    resources:
    - topologies/status
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedtn-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: kubedtn-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubedtn
